import os
from dotenv import load_dotenv

load_dotenv()

TWITTER_CONSUMER_KEY=os.getenv("CONSUMER_KEY")
TWITTER_CONSUMER_SECRET=os.getenv("CONSUMER_SECRET")
TWITTER_ACCESS_TOKEN=os.getenv("ACCESS_TOKEN")
TWITTER_ACCESS_TOKEN_SECRET=os.getenv("ACCESS_TOKEN_SECRET")

AWS_ACCESSS_KEY=os.getenv("AWS_ACCESS_KEY")
AWS_ACCESS_SECRET=os.getenv("AWS_ACCESS_SECRET")

SRC_PATH=os.getenv("SRC_PATH")
DEST_PATH=os.getenv("DEST_PATH")