import os
from dotenv import load_dotenv

load_dotenv()

TWITTER_CONSUMER_KEY=os.getenv("CONSUMER_KEY")
TWITTER_CONSUMER_SECRET=os.getenv("CONSUMER_SECRET")
TWITTER_ACCESS_TOKEN=os.getenv("ACCESS_TOKEN")
TWITTER_ACCESS_TOKEN_SECRET=os.getenv("ACCESS_TOKEN_SECRET")